options:
  env:
    - SERVER_IMAGE_NAME=eu.gcr.io/$PROJECT_ID/random-github-server-$_STAGE:$COMMIT_SHA
steps:  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-server'
    entrypoint: bash
    args: ['-c', 'docker build -t $$SERVER_IMAGE_NAME -f Dockerfile.server .']
    waitFor: ['-']
    
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-server'
    entrypoint: bash
    args: ['-c', 'docker push $$SERVER_IMAGE_NAME']
    waitFor: ['build-server']
images:
  - eu.gcr.io/$PROJECT_ID/random-github-server-$_STAGE:$COMMIT_SHA
