name: 'Build Backend'

on: 
  workflow_dispatch:

env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  IMAGE: random-github-server
  REGISTRY_HOSTNAME: gcr.io

jobs:
  Build and publish docker image:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCR_KEY }} 

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        gcloud auth configure-docker

    - name: Build image
      run: |
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
        echo $TAG
        docker build -t "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .

    - name: Publish image
      run: |
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
        echo $TAG
        docker push "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG"
        docker tag "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG" "$REGISTRY_HOSTNAME"/"$IMAGE":latest
        docker push "$REGISTRY_HOSTNAME"/"$IMAGE":latest

  # terraform:
  #   name: 'Terraform'
  #   runs-on: ubuntu-latest
  #   env:
  #     working-directory: ./backend
    
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
    
  #   - name: Setup Terraform
  #     uses: hashicorp/setup-terraform@v1
      
  #   - name: Terraform Init
  #     run: terraform init
  #     working-directory: ${{ env.working-directory }}
  #     env:
  #       GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  #   - name: Terraform Plan
  #     run: |-
  #       terraform plan \
  #       -var 'github_access_token=$ACCESS_TOKEN_GITHUB' \
  #       -var 'commit_sha=$COMMIT_SHA'
  #     working-directory: ${{ env.working-directory }}
  #     env:
  #       GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
  #   - name: Terraform Apply
  #     run: |-
  #       terraform apply \
  #       -var 'github_access_token=$ACCESS_TOKEN_GITHUB' \
  #       -var 'commit_sha=$COMMIT_SHA' \
  #       -auto-approve
  #     working-directory: ${{ env.working-directory }}
  #     env:
  #       GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}