name: 'Build Frontend'

on: 
  workflow_dispatch:
  
  push:
    tags:
      - 'frontend-v*'

env:
  IMAGE_NAME: random-github-frontend-production
  WORKING_DIRECTORY: ./frontend
  GITHUB_SHA: $GITHUB_SHA

jobs:
  build_and_publish_docker_image:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GCR_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCR_KEY }}
        project_id: ${{ secrets.GCR_PROJECT_ID }}
  
    - name: Create env file
      run: |
        touch .env
        echo NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL_PROD }} >> .env
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Build
      run: |-
        gcloud builds submit --tag "eu.gcr.io/${{ secrets.GCR_PROJECT_ID }}/$IMAGE_NAME:$GITHUB_SHA" 
      working-directory: ${{ env.WORKING_DIRECTORY }}

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: [build_and_publish_docker_image]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform force unlock
      run: terraform force-unlock -force 1633870084444399
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Plan
      run: |-
        terraform plan \
        -var "commit_sha=$GITHUB_SHA"
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
    - name: Terraform Apply
      run: |-
        terraform apply \
        -var "commit_sha=$GITHUB_SHA" \
        -auto-approve
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}