name: 'Build Frontend'

on: 
  workflow_dispatch:

env:
  IMAGE_NAME: random-github-frontend-production
  WORKING_DIRECTORY: ./frontend
  GITHUB_SHA: $GITHUB_SHA

jobs:
  build_and_publish_docker_image:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GCR_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCR_KEY }}
        project_id: ${{ secrets.GCR_PROJECT_ID }}
    
    - name: Build
      run: |-
        gcloud builds submit --tag "eu.gcr.io/${{ secrets.GCR_PROJECT_ID }}/$IMAGE_NAME:$GITHUB_SHA" 
      working-directory: ${{ env.WORKING_DIRECTORY }}
    