name: 'Build Backend'

on: 
  workflow_dispatch:
  
  push:
    tags:
      - 'server-v*'

env:
  IMAGE_NAME: random-github-server-production
  WORKING_DIRECTORY: ./backend
  GITHUB_SHA: $GITHUB_SHA

jobs:
  build_and_publish_docker_image:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GCR_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCR_KEY }}
        project_id: ${{ secrets.GCR_PROJECT_ID }}
    
    - name: Build
      run: |-
        gcloud builds submit --tag "eu.gcr.io/${{ secrets.GCR_PROJECT_ID }}/$IMAGE_NAME:$GITHUB_SHA" 
      working-directory: ${{ env.WORKING_DIRECTORY }}
    

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: [build_and_publish_docker_image]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Plan
      run: |-
        terraform plan \
        -var 'github_access_token=$ACCESS_TOKEN_GITHUB' \
        -var 'commit_sha=$GITHUB_SHA'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
    - name: Terraform Apply
      run: |-
        terraform apply \
        -var "github_access_token=$ACCESS_TOKEN_GITHUB" \
        -var "commit_sha=$GITHUB_SHA" \
        -auto-approve
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}